name: Label Approved

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  pull-requests: write

jobs:
  label-approved:
    runs-on: ubuntu-latest
    steps:
    - uses: tiangolo/label-approved@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        debug: true
